### ISSUE TITLE
[Notice] Homework (10/31)

### ISSUE THREAD

**Issue by unizard** [sejongresearch/2019.Fall.PatternRecognition#21]
## 과제
- 중간고사 4,5번 문제를 과제로 풀어 제출하세요.
- 마감시간은 10월 31일 오후 11시 59분입니다.
- 캐글 리더보드에 제출과 동시에 ipynb 를 제출하셔야 합니다.

## 링크
- [4번](https://www.kaggle.com/c/2019-fall-pr-project)
- [5번](https://www.kaggle.com/c/2019-pr-midterm-musicclassification)

**Comment by big-chan** [comment]
혹시 성능에 의해 과제 점수가 달라지나요..?

**Comment by unizard** [comment]
@big-chan 네 달라지지 않습니다만, 기본 일정 이하의 정확도를 보이는 것은 숙제를 잘못한 것이겠죠?
