### ISSUE TITLE
[HW] Label(Class) mismatch

### ISSUE THREAD

**Issue by socome** [sejongresearch/2019.Fall.PatternRecognition#26]
과제로 주어진 중간고사 5번문제에서 라벨이 시험지와 매칭되지 않습니다. 

시험지에서는 

blues (0),classical (6),country (1),disco(7),hiphop(5),jazz (3),metal (9),pop (8),reggae(4),rock(2)

로 나타나있지만 해당 클래스별로 분류하면 성능이 20퍼센트정도 나옵니다.  이를 다음과 같이 알파벳 순으로 변경하면 성능이 70퍼센트까지 오르는 것으로 보아 시험지 라벨표기가 잘못된 것 같습니다.

blues (0),classical (1),country (2),disco(3),hiphop(4),jazz (5),metal (6),pop (7),reggae(8),rock(9)

**Comment by min942773** [comment]
감사합니다!
